const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const source = fs.readFileSync(path.join(root, 'src', 'extension.ts'), 'utf8');
const commands = new Set(pkg.contributes.commands.map(item => item.command));

for (const command of ['arduinoFirstRunAgent.dashboard', 'arduinoFirstRunAgent.toggleDashboard', 'arduinoFirstRunAgent.openStartupSettings', 'arduinoFirstRunAgent.simulate', 'arduinoFirstRunAgent.exportCommunity']) assert.ok(commands.has(command), `${command} must be user-accessible`);
for (const capability of ['chooseBeginnerHardware', 'confirmGeneratedPlanInPanel', 'installProjectLibraries', 'compileWithPlatformRecovery', 'repairGeneratedProject', 'confirmWiring', 'exportSafetyIssues', 'THIRD_PARTY_NOTICES.md']) assert.match(source, new RegExp(capability.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `${capability} must remain in the integrated flow`);
for (const capability of ['beginnerHardwareDraft', 'installedLibraryDetails', 'licenseText', 'reproducibleEnvironment', 'build-environment.json', 'THIRD_PARTY_LICENSES/', 'evaluateProvenanceTerminals(spec, packPath)']) assert.match(source, new RegExp(capability.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `${capability} must remain covered by product acceptance`);
for (const capability of ['startWithNewProject', 'openDashboardOnStartup', 'openStartupSettings', 'startupSuppressedFile', "workspaceState.update('projectDraft', '')"]) assert.match(source, new RegExp(capability.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `${capability} must remain in startup preferences behavior`);
assert.equal(pkg.contributes.configuration.properties['arduinoAgent.startWithNewProject'].default, true);
assert.equal(pkg.contributes.configuration.properties['arduinoAgent.openDashboardOnStartup'].default, true);
assert.match(source, /function startupSettingsHtml\(/, 'startup preferences must render inside the Agent dashboard');
assert.match(source, /message\.type === 'saveStartupSettings'/, 'startup preferences must save from the dashboard without a top quick-pick');
assert.match(source, /executeCommand\('arduino-new-sketch'\)/, 'startup must open a real new Arduino sketch instead of retaining the previous .ino editor');
assert.match(source, /isRestoredIno && !isAlreadyFreshSketch/, 'a fresh temporary sketch must never recursively create another sketch');
assert.ok((pkg.activationEvents || []).includes('onStartupFinished'), 'extension must activate with Arduino IDE startup so a later user click cannot trigger startup sketch creation');
assert.ok(!(pkg.activationEvents || []).some(item => item.startsWith('onView:')), 'legacy sidebar view must not activate the extension');
assert.equal(pkg.contributes.views, undefined, 'legacy Agent tree view must stay removed');
assert.equal(pkg.contributes.viewsContainers, undefined, 'legacy Agent activity-bar container must stay removed');
assert.equal(pkg.contributes.commands.find(item => item.command === 'arduinoFirstRunAgent.toggleDashboard')?.title, '⚡ Arduino Agent 看板（打开 / 关闭）', 'the dashboard toggle must combine a recognizable visual marker with an explicit action');
assert.equal(pkg.contributes.commands.find(item => item.command === 'arduinoFirstRunAgent.toggleDashboard')?.icon, undefined, 'the dashboard toggle must render as an explicit text action instead of an icon-only control');
assert.ok((pkg.contributes.menus?.['editor/title'] || []).some(item => item.command === 'arduinoFirstRunAgent.toggleDashboard' && item.group.startsWith('navigation')), 'the dashboard toggle must remain prominent in the editor title bar');
assert.doesNotMatch(source, /createStatusBarItem\('arduinoFirstRunAgent\.toggleDashboard'/, 'the primary Agent toggle must not be hidden in the status bar');
assert.match(source, /if \(dashboardPanel\) \{\s*dashboardPanel\.dispose\(\);\s*return;/, 'the dashboard toggle must close an open dashboard');
assert.match(source, /executeCommand\('arduinoFirstRunAgent\.dashboard'\)/, 'the dashboard toggle must reopen a closed dashboard');
assert.match(source, /data-command="arduinoFirstRunAgent\.toggleDashboard">◀ 收起 Agent 看板</, 'the labeled close action must use the same tested toggle command as the persistent entry point');
assert.match(source, /spec\.components\.map\(component => localHardwarePackMatch/);
assert.match(source, /does not guarantee bit-for-bit reproducible output/);
assert.match(source, /已启动 SimulIDE，等待用户建立电路并运行；尚未取得自动化结果/);
assert.match(source, /API Key、串口地址、本机路径、临时文件/);
assert.match(source, /实物验证/);
assert.match(source, /Fritzing辅助端子，不能覆盖官方契约/);
assert.match(source, /compilePassed = state\.evidence\.some/, 'simulation and community export must be gated by real compile evidence');
assert.match(source, /brief\?\.projectFile && existsSync\(brief\.projectFile\) \? brief\.projectFile : currentSketch\(\)\?\.file/, 'open-current-code must prefer the Agent project instead of an unrelated active tab');
assert.match(source, /方案确认页面被关闭，需求已保留，可以继续重试/, 'closing confirmation must become a recoverable state instead of a dead end');
for (const token of ['agentWorkbenchThemeCss', '--lab-signal', '--lab-muted:#b7ced9', 'main{position:relative;background-color:transparent!important', '.setting{background-color:rgba(13,29,43,.94)!important', '.option em,li span,.connection i,.confidence.not-run span', 'input::placeholder,textarea::placeholder{color:#9bb7c5!important', 'button:disabled{opacity:.72!important', '.step,.step small,.step span{color:#bfe3ef', '.mini span{color:#8fd8f4', 'labPulse', 'prefers-reduced-motion', 'themedAgentHtml']) assert.match(source, new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `${token} must remain in the electronic-workbench visual system`);
console.log('integrated product flow acceptance tests passed');
