const assert = require('node:assert/strict');
const fs = require('node:fs');
const source = fs.readFileSync(require.resolve('../dist/extension'), 'utf8');
const marker = source.indexOf('hardwareIndexes:');
assert.ok(marker > 0, 'temporary plan editor script should exist');
const start = source.lastIndexOf('<script>', marker);
const end = source.indexOf('</script>', marker);
assert.ok(start >= 0 && end > start, 'temporary plan editor script should be extractable');
const script = source.slice(start + '<script>'.length, end);
assert.doesNotThrow(() => new Function(script), 'temporary plan editor JavaScript must be syntactically valid after template compilation');
assert.match(script, /String\.fromCharCode\(10\)/, 'line splitting must not embed a literal newline inside a regex');
const dependencyMarker = source.indexOf('hardwareChanged,plan:');
assert.ok(dependencyMarker > 0, 'dependency-aware hardware editor script should exist');
const dependencyStart = source.lastIndexOf('<script>', dependencyMarker);
const dependencyEnd = source.indexOf('</script>', dependencyMarker);
assert.ok(dependencyStart >= 0 && dependencyEnd > dependencyStart);
const dependencyScript = source.slice(dependencyStart + '<script>'.length, dependencyEnd);
assert.doesNotThrow(() => new Function(dependencyScript), 'dependency-aware editor JavaScript must be syntactically valid');
assert.match(source, /硬件已改变：仍可继续编辑/);
assert.match(source, /撤销本页修改/);
assert.match(source, /target\.dataset\.message==='editGoal'\|\|target\.dataset\.message==='editHardware'/);
assert.match(source, /你最初描述的需求/);
assert.match(source, /核心\/必须/);
assert.match(source, /复杂项目不能只提供开发板一个选择组/);
assert.match(source, /声音提醒设备/);
assert.match(source, /灯光提醒设备/);
assert.match(source, /本身不能完成项目/);
assert.match(source, /function resolveModelRoles/);
assert.match(source, /规划模型/);
assert.match(source, /审查模型/);
assert.match(source, /uniqueModels/);
assert.match(source, /确认所需硬件与方案/);
assert.match(source, /editBeginnerPlanWithDependencies\(plan, selected, fuzzyGoal, true, hostPanel, restoreHost\)/);
assert.match(source, /hostPanel \|\| plugin\.window\.createWebviewPanel\('arduinoHardwareDecisions'/);
assert.match(source, /确认并生成代码/);
assert.match(source, /confirmGeneratedPlanInPanel/);
assert.match(source, /每个选项都提供外观参考和淘宝搜索/);
assert.match(source, /确认上传目标/);
assert.match(source, /behaviorFeedbackHtml/);
assert.match(source, /behaviorDiagnosisHtml/);
assert.match(source, /confirmRevisionInPanel/);
assert.doesNotMatch(source, /createWebviewPanel\('arduinoAgentWiring'/);
assert.doesNotMatch(source, /选择要上传的 Arduino 串口/);
assert.doesNotMatch(source, /请选择实物运行结果/);
assert.doesNotMatch(source, /请补充你看到的现象/);
assert.match(source, /projectComposerVisible/);
assert.match(source, /showComposer \?/);
assert.match(source, /AI 服务设置/);
assert.match(source, /ARDUINO AGENT SETTINGS/);
assert.match(source, /保存启动设置/);
assert.match(source, /type:'saveStartupSettings'/);
assert.doesNotMatch(source, /canPickMany:!0,placeHolder:"勾选需要在 Arduino IDE 启动时自动执行的操作"/);
assert.match(source, /saveAiSettings/);
assert.match(source, /测试并保存/);
assert.match(source, /查看具体原因/);
assert.match(source, /保留当前需求并重试/);
assert.match(source, /逐项核对实际效果/);
assert.match(source, /confirmObservedCriteria/);
assert.match(source, /Agent 无法通过普通 USB 看见实际导线/);
assert.match(source, /AI 返回了相同的代码，没有修复编译错误/);
assert.match(source, /data-message="editGoal"/);
assert.match(source, /Agent 正在进行第/);
assert.match(source, /上一轮完整生成失败，必须主动修正且不要重复/);
assert.match(source, /recoveryAttempt < 3/);
assert.match(source, /查看外观与淘宝搜索/);
assert.match(source, /hardwareImageHtml\(item\)/);
assert.match(source, /grid-template-columns:22px minmax\(0,1fr\)/);
assert.match(source, /overflow-wrap:anywhere/);
assert.match(source, /\.option-copy\{grid-column:2;min-width:0\}/);
assert.match(source, /type:'openPurchase'/);
assert.match(source, /AI 服务网关暂时无响应/);
assert.match(source, /服务商返回了无法解析的网页错误/);
assert.match(source, /function requestAiWithRetry/);
assert.match(source, /progressively smaller reservation/);
assert.match(source, /真实代码修复能力测试失败/);
assert.match(source, /max_tokens: 6000/);
assert.match(source, /408, 409, 425, 429, 500, 502, 503, 504/);
assert.match(source, /保留需求，继续重试/);
assert.match(source, /修改原始描述/);
assert.match(source, /检查 AI 设置/);
assert.match(source, /查看错误详情/);
assert.match(source, /skipBeginnerWizard/);
assert.match(source, /id="projectGoal"/);
assert.match(source, /min-height:180px/);
assert.match(source, /type:'startProject'/);
assert.match(source, /所有输入都留在项目看板中/);
assert.doesNotMatch(source, /data-command="arduinoFirstRunAgent\.benchmark"/);
assert.doesNotMatch(source, /class="benchmark-entry"/);
assert.doesNotMatch(source, /spec\?\.connections\.slice\(0, 12\)/, 'the dashboard must not silently omit safety-critical wiring');
console.log('webview script tests passed');
