export type EvidenceLevel = 'official-datasheet' | 'official-library' | 'community-reference';

export type HardwareContract = {
  id: string;
  name: string;
  aliases: readonly string[];
  match: RegExp;
  variantWarning?: string;
  interface: string;
  signalPins: readonly string[];
  powerPins: readonly string[];
  voltage?: string;
  libraries?: readonly string[];
  evidence: readonly { level: EvidenceLevel; title: string; url: string }[];
};

export const hardwareContracts: readonly HardwareContract[] = [
  { id: 'bmp280', name: 'BMP280', aliases: ['气压传感器'], match: /BMP\s*280/i, variantWarning: '模块可能是I2C或SPI，按丝印确认接口', interface: 'I2C或SPI', signalPins: ['SDA/SCL 或 SCK/SDI/SDO/CS'], powerPins: ['VIN/VCC', 'GND'], voltage: '1.8V-3.6V芯片；模块按板载稳压', libraries: ['Adafruit BMP280 Library'], evidence: [{ level: 'official-datasheet', title: 'Bosch BMP280 datasheet', url: 'https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmp280-ds001.pdf' }, { level: 'official-library', title: 'Adafruit BMP280 library', url: 'https://github.com/adafruit/Adafruit_BMP280_Library' }] },
  { id: 'mpu6050', name: 'MPU6050', aliases: ['六轴姿态传感器'], match: /MPU[- ]?6050|GY[- ]?521/i, interface: 'I2C', signalPins: ['SDA', 'SCL', 'INT(可选)'], powerPins: ['VCC', 'GND'], voltage: '3.3V芯片；模块按板载稳压', libraries: ['Adafruit MPU6050'], evidence: [{ level: 'official-datasheet', title: 'TDK InvenSense MPU-6050', url: 'https://invensense.tdk.com/products/motion-tracking/6-axis/mpu-6050/' }, { level: 'official-library', title: 'Adafruit MPU6050 library', url: 'https://github.com/adafruit/Adafruit_MPU6050' }] },
  { id: 'hc05', name: 'HC-05', aliases: ['蓝牙串口模块'], match: /HC\s*-?05/i, variantWarning: 'RX为3.3V逻辑，Arduino 5V TX需分压或电平转换；不同克隆板端子可能不同', interface: 'UART', signalPins: ['TXD', 'RXD', 'STATE(可选)', 'EN(可选)'], powerPins: ['VCC', 'GND'], voltage: '3.3V逻辑', libraries: ['SoftwareSerial'], evidence: [{ level: 'community-reference', title: 'Components101 HC-05 reference', url: 'https://components101.com/wireless/hc-05-bluetooth-module' }] },
  { id: 'nrf24l01', name: 'nRF24L01+', aliases: ['2.4GHz无线模块'], match: /nRF[ -]?24L01/i, variantWarning: '必须使用稳定3.3V供电，模块旁建议去耦电容', interface: 'SPI', signalPins: ['CE', 'CSN', 'SCK', 'MOSI', 'MISO', 'IRQ(可选)'], powerPins: ['VCC', 'GND'], voltage: '3.3V', libraries: ['RF24'], evidence: [{ level: 'official-datasheet', title: 'Nordic nRF24L01+ product specification', url: 'https://infocenter.nordicsemi.com/pdf/nRF24L01P_PS_v1.0.pdf' }, { level: 'official-library', title: 'RF24 library', url: 'https://github.com/nRF24/RF24' }] },
  { id: 'tm1637', name: 'TM1637', aliases: ['四位数码管'], match: /TM1637|四位数码管/i, interface: '两线时序', signalPins: ['CLK', 'DIO'], powerPins: ['VCC', 'GND'], voltage: '5V', libraries: ['TM1637Display'], evidence: [{ level: 'official-library', title: 'TM1637Display library', url: 'https://github.com/avishorp/TM1637' }] },
  { id: 'ads1115', name: 'ADS1115', aliases: ['16位ADC'], match: /ADS[ -]?1115/i, interface: 'I2C', signalPins: ['SDA', 'SCL', 'ADDR', 'ALERT(可选)'], powerPins: ['VDD', 'GND'], voltage: '2.0V-5.5V', libraries: ['Adafruit ADS1X15'], evidence: [{ level: 'official-datasheet', title: 'Texas Instruments ADS1115', url: 'https://www.ti.com/product/ADS1115' }, { level: 'official-library', title: 'Adafruit ADS1X15 library', url: 'https://github.com/adafruit/Adafruit_ADS1X15' }] },
  { id: 'hc-sr04', name: 'HC-SR04', aliases: ['超声波测距模块'], match: /HC-?SR04|超声波测距/i, interface: 'TRIG/ECHO', signalPins: ['TRIG', 'ECHO'], powerPins: ['VCC', 'GND'], voltage: '5V', evidence: [{ level: 'community-reference', title: 'Wokwi HC-SR04 reference', url: 'https://docs.wokwi.com/parts/wokwi-hc-sr04' }] },
  { id: 'dht22', name: 'DHT22/AM2302', aliases: ['温湿度传感器'], match: /DHT\s*22|AM2302/i, variantWarning: '裸四脚器件与三脚模块的引脚顺序不同', interface: '单线数字', signalPins: ['DATA'], powerPins: ['VCC', 'GND'], voltage: '3.3V-5V', libraries: ['DHT sensor library'], evidence: [{ level: 'official-library', title: 'Adafruit DHT sensor library', url: 'https://github.com/adafruit/DHT-sensor-library' }] },
  { id: 'ds18b20', name: 'DS18B20', aliases: ['防水温度探头'], match: /DS18B20/i, variantWarning: '裸器件和防水探头线色需按卖家资料确认', interface: 'OneWire', signalPins: ['DATA'], powerPins: ['VCC', 'GND'], voltage: '3.0V-5.5V', libraries: ['OneWire', 'DallasTemperature'], evidence: [{ level: 'official-datasheet', title: 'Analog Devices DS18B20 product page', url: 'https://www.analog.com/en/products/ds18b20.html' }, { level: 'official-library', title: 'DallasTemperature library', url: 'https://github.com/milesburton/Arduino-Temperature-Control-Library' }] },
  { id: 'ws2812b', name: 'WS2812B', aliases: ['NeoPixel', '可寻址灯带'], match: /WS2812B?|NeoPixel/i, interface: '单线可寻址', signalPins: ['DIN'], powerPins: ['5V', 'GND'], voltage: '5V', libraries: ['Adafruit NeoPixel'], evidence: [{ level: 'official-library', title: 'Adafruit NeoPixel library', url: 'https://github.com/adafruit/Adafruit_NeoPixel' }] },
  { id: 'tcs34725', name: 'TCS34725', aliases: ['颜色传感器'], match: /TCS34725/i, interface: 'I2C', signalPins: ['SDA', 'SCL'], powerPins: ['VIN', 'GND'], libraries: ['Adafruit TCS34725'], evidence: [{ level: 'official-datasheet', title: 'ams OSRAM TCS34725', url: 'https://ams-osram.com/products/sensor-solutions/ambient-light-color-spectral-proximity-sensors/ams-tcs34725-color-sensor' }, { level: 'official-library', title: 'Adafruit TCS34725 library', url: 'https://github.com/adafruit/Adafruit_TCS34725' }] },
  { id: 'apds9960', name: 'APDS-9960', aliases: ['手势传感器'], match: /APDS-?9960/i, interface: 'I2C', signalPins: ['SDA', 'SCL'], powerPins: ['VIN', 'GND'], libraries: ['Adafruit APDS9960 Library'], evidence: [{ level: 'official-library', title: 'Adafruit APDS9960 library', url: 'https://github.com/adafruit/Adafruit_APDS9960' }] },
  { id: 'mfrc522', name: 'MFRC522/RC522', aliases: ['RFID读卡器'], match: /MFRC522|\bRC522\b/i, variantWarning: '芯片逻辑为3.3V；不同模块是否自带电平适配必须确认', interface: 'SPI', signalPins: ['SCK', 'MOSI', 'MISO', 'SS', 'RST'], powerPins: ['3.3V', 'GND'], voltage: '3.3V', libraries: ['MFRC522'], evidence: [{ level: 'official-datasheet', title: 'NXP MFRC522 product page', url: 'https://www.nxp.com/products/rfid-nfc/nfc-hf/nfc-readers/standard-performance-mifare-and-ntag-frontend:MFRC52202HN1' }, { level: 'official-library', title: 'Arduino MFRC522 library', url: 'https://github.com/miguelbalboa/rfid' }] },
  { id: 'hx711', name: 'HX711', aliases: ['称重放大器'], match: /HX711/i, variantWarning: '称重传感器线色没有统一标准，必须按具体传感器资料确认E+/E-/A+/A-', interface: '双线时钟数据', signalPins: ['DT', 'SCK'], powerPins: ['VCC', 'GND'], voltage: '2.6V-5.5V', libraries: ['HX711'], evidence: [{ level: 'official-library', title: 'bogde HX711 library', url: 'https://github.com/bogde/HX711' }] },
  { id: 'a4988', name: 'A4988', aliases: ['步进电机驱动器'], match: /A4988/i, variantWarning: '必须按电机额定电流调节限流，VMOT旁需要合适的去耦电容', interface: 'STEP/DIR', signalPins: ['STEP', 'DIR', 'EN'], powerPins: ['VDD', 'GND', 'VMOT', 'GND'], evidence: [{ level: 'official-datasheet', title: 'Allegro A4988', url: 'https://www.allegromicro.com/en/products/motor-drivers/brush-dc-motor-drivers/a4988' }] },
  { id: 'ds3231', name: 'DS3231', aliases: ['实时时钟'], match: /DS3231/i, interface: 'I2C', signalPins: ['SDA', 'SCL'], powerPins: ['VCC', 'GND'], libraries: ['RTClib'], evidence: [{ level: 'official-datasheet', title: 'Analog Devices DS3231 product page', url: 'https://www.analog.com/en/products/ds3231.html' }, { level: 'official-library', title: 'Adafruit RTClib', url: 'https://github.com/adafruit/RTClib' }] },
  { id: 'max7219', name: 'MAX7219', aliases: ['8x8点阵驱动'], match: /MAX7219|MAX72XX/i, interface: 'SPI类三线', signalPins: ['DIN', 'CLK', 'CS'], powerPins: ['VCC', 'GND'], voltage: '5V', libraries: ['MD_MAX72XX'], evidence: [{ level: 'official-datasheet', title: 'Analog Devices MAX7219 product page', url: 'https://www.analog.com/en/products/max7219.html' }, { level: 'official-library', title: 'MD_MAX72XX library', url: 'https://github.com/MajicDesigns/MD_MAX72XX' }] },
  { id: 'bme280', name: 'BME280', aliases: ['温湿度气压传感器'], match: /BME280/i, variantWarning: '模块可能配置为I2C或SPI，必须与所选模块端子一致', interface: 'I2C或SPI', signalPins: ['SDA/SCL 或 SCK/SDI/SDO/CS'], powerPins: ['VIN', 'GND'], evidence: [{ level: 'official-datasheet', title: 'Bosch BME280', url: 'https://www.bosch-sensortec.com/products/environmental-sensors/humidity-sensors-bme280/' }] },
  { id: 'ssd1306', name: 'SSD1306 OLED', aliases: ['OLED显示屏'], match: /SSD1306/i, variantWarning: '常见模块可能是I2C或SPI，必须按具体端子确认', interface: 'I2C或SPI', signalPins: ['SDA/SCL 或 SCK/MOSI/CS/DC/RST'], powerPins: ['VCC', 'GND'], libraries: ['Adafruit SSD1306'], evidence: [{ level: 'official-datasheet', title: 'Solomon Systech SSD1306', url: 'https://www.solomon-systech.com/product/ssd1306/' }, { level: 'official-library', title: 'Adafruit SSD1306 library', url: 'https://github.com/adafruit/Adafruit_SSD1306' }] },
  { id: 'pn532', name: 'PN532', aliases: ['NFC模块'], match: /PN532/i, variantWarning: '模块可配置I2C、SPI或HSU，拨码开关必须与代码一致', interface: 'I2C/SPI/UART', signalPins: ['按所选接口'], powerPins: ['VCC', 'GND'], voltage: '3.3V逻辑；模块供电按厂商说明', libraries: ['Adafruit PN532'], evidence: [{ level: 'official-library', title: 'Adafruit PN532 library and examples', url: 'https://github.com/adafruit/Adafruit-PN532' }] },
  { id: 'pca9685', name: 'PCA9685', aliases: ['16路舵机驱动板'], match: /PCA9685/i, variantWarning: '舵机电源V+与逻辑VCC分开，必须共地', interface: 'I2C', signalPins: ['SDA', 'SCL', 'OE(可选)'], powerPins: ['VCC', 'GND', 'V+'], libraries: ['Adafruit PWM Servo Driver Library'], evidence: [{ level: 'official-datasheet', title: 'NXP PCA9685', url: 'https://www.nxp.com/products/power-drivers/lighting-driver-and-controller-ics/led-drivers/16-channel-12-bit-pwm-fm-plus-ic-bus-led-driver:PCA9685' }, { level: 'official-library', title: 'Adafruit PWM Servo Driver library', url: 'https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library' }] },
  { id: 'l298n', name: 'L298N模块', aliases: ['双路直流电机驱动器'], match: /L298N/i, variantWarning: '不同模块的5V_EN跳帽和板载稳压用法不同，按模块丝印确认', interface: 'ENA/IN1/IN2/IN3/IN4/ENB', signalPins: ['ENA', 'IN1', 'IN2', 'IN3', 'IN4', 'ENB'], powerPins: ['VS', '5V逻辑', 'GND'], voltage: '电机电源与逻辑电源分离', evidence: [{ level: 'official-datasheet', title: 'ST L298 datasheet', url: 'https://www.st.com/resource/en/datasheet/l298.pdf' }] },
  { id: 'vl53l0x', name: 'VL53L0X', aliases: ['激光测距模块'], match: /VL53L0X/i, interface: 'I2C', signalPins: ['SDA', 'SCL', 'XSHUT(可选)', 'GPIO1(可选)'], powerPins: ['VIN/VDD', 'GND'], voltage: '2.8V芯片；模块按板载稳压', libraries: ['Adafruit VL53L0X'], evidence: [{ level: 'official-datasheet', title: 'ST VL53L0X', url: 'https://www.st.com/en/imaging-and-photonics-solutions/vl53l0x.html' }, { level: 'official-library', title: 'Adafruit VL53L0X library', url: 'https://github.com/adafruit/Adafruit_VL53L0X' }] },
  { id: 'ina219', name: 'INA219', aliases: ['电流电压传感器'], match: /INA219/i, interface: 'I2C', signalPins: ['SDA', 'SCL'], powerPins: ['VCC', 'GND', 'VIN+', 'VIN-'], voltage: '3V-5.5V逻辑', libraries: ['Adafruit INA219'], evidence: [{ level: 'official-datasheet', title: 'Texas Instruments INA219', url: 'https://www.ti.com/product/INA219' }, { level: 'official-library', title: 'Adafruit INA219 library', url: 'https://github.com/adafruit/Adafruit_INA219' }] }
];

export function contractsFor(text: string): readonly HardwareContract[] {
  return hardwareContracts.filter(contract => contract.match.test(text));
}

export function verifiedContractKnowledge(text: string): string {
  return contractsFor(text).map(contract => {
    const libraries = contract.libraries?.length ? `；库=${contract.libraries.join(',')}` : '';
    const warning = contract.variantWarning ? `；变体警告=${contract.variantWarning}` : '';
    const evidence = contract.evidence.map(item => `${item.level}:${item.url}`).join(',');
    return `[已验证契约 ${contract.id}] ${contract.name}；接口=${contract.interface}；信号端子=${contract.signalPins.join('/')}；供电端子=${contract.powerPins.join('/')}；电压=${contract.voltage || '按具体模块'}${libraries}${warning}；证据=${evidence}`;
  }).join('\n');
}
